name: LittleAlchemy2Text
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2024.3.11=hca03da5_0
  - libffi=3.4.4=hca03da5_1
  - ncurses=6.4=h313beb8_0
  - openssl=3.0.14=h80987f9_0
  - pip=24.0=py311hca03da5_0
  - python=3.11.9=hb885b13_0
  - readline=8.2=h1a28f6b_0
  - setuptools=69.5.1=py311hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - tk=8.6.14=h6ba3021_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.43.0=py311hca03da5_0
  - xz=5.4.6=h80987f9_1
  - zlib=1.2.13=h18a0788_1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.4.0
      - blinker==1.8.2
      - blis==0.7.11
      - catalogue==2.0.10
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpathlib==0.18.1
      - cloudpickle==3.0.0
      - confection==0.1.5
      - cymem==2.0.8
      - filelock==3.15.4
      - flask==3.0.3
      - fsspec==2024.6.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.7
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - langcodes==3.4.0
      - language-data==1.2.0
      - marisa-trie==1.2.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - murmurhash==1.0.10
      - networkx==3.3
      - numpy==1.26.4
      - ollama==0.2.1
      - packaging==24.1
      - preshed==3.0.9
      - pydantic==2.7.4
      - pydantic-core==2.18.4
      - pygments==2.18.0
      - python-box==7.2.0
      - requests==2.32.3
      - rich==13.7.1
      - shellingham==1.5.4
      - smart-open==7.0.4
      - sniffio==1.3.1
      - spacy==3.7.5
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - sympy==1.12.1
      - thinc==8.2.5
      - torch==2.3.1
      - tqdm==4.66.4
      - typer==0.12.3
      - typing-extensions==4.12.2
      - urllib3==2.2.2
      - wasabi==1.1.3
      - weasel==0.4.1
      - werkzeug==3.0.3
      - wrapt==1.16.0
prefix: /Users/enis/miniconda3/envs/LittleAlchemy2Text
